server:
  port: 8095
  servlet:  
    context-path: /vet  
spring:   
  application:
    name: vet-service  
  datasource: 
    url: jdbc:postgresql://localhost:54321/vetBT?CreateDatabaseIfNotExist=true
    username: postgres
    password: root  

    driver-class-name: org.postgresql.Driver   
  jpa:  
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect 
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
  cloud:
    discovery:
      enabled: false
      
swagger:  
  url: http://localhost:8095/vet
  

    



